### ISSUE TITLE
Render build artifacts from `dbtCLI` with custom project directory

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-dbt#46]
## Problem

Currently, the `dbtCLI` task only returns build artifacts when using the root project directory. When setting custom `--profiles-dir /app --project-dir /app` which is important when dbt project is baked into the Docker image or Docker volume, this task fails to identify the `manifest.json` to render the dbt DAG.

## Possible solution

Add a property `projectDir` to allow either:
- switching to that working directory before starting dbt commands
- allow specifying explicitly the path where Kestra can find the run artifacts incl. `manifest.json` to render the DAG for the Gantt view

**Comment by loicmathieu** [comment]
@anna-geller we will need to add a new property for that, it can be:
- projectDir so we change the working directory to it (instead of using --project-dir), it can makes using --profile-dir less easy
- artifactDir so we search for artifact in this directory, in this case this will be up to the user to use artifactDir when he use -profile-dir

Both works for me, which one do you prefer?

**Comment by anna-geller** [comment]
thanks so much, let me cross-check both options with @Ben8t and get back to you 👍

**Comment by anna-geller** [comment]
currently I have to do some hacks like so:

https://github.com/kestra-io/course/blob/duckdb/flows/03_dbt_dev_initial.yml#L21-L24

if both properties projectDir and profilesDir would be available, I could remove that part from my flow

**Comment by loicmathieu** [comment]
Setting both is not easy, I don't want to hook into the DbtCLI command the user wrote, so my proposition was to change the working directory or search for artifacts in a specific directory.

Setting the profiledDir can only be done by adding an option in the dbt CLI command, that's why I didn't want to offer this solution as a task property.
